project:
  type: website
  output-dir: _site

website:
  title: "FAA Flight Delay Analysis"
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
